name: Check Merge Conflicts

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  Label:
    if: ( github.event.pull_request.draft == false ) && ( github.actor != 'PJBot' && github.actor != 'Polonium-bot' )
    runs-on: ubuntu-latest
    steps:
      - name: Check for Merge Conflicts
        uses: eps1lon/actions-label-merge-conflict@v3.0.0
        with:
          dirtyLabel: "(/) Konflikt Scalania"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "Ten pull request ma konflikty, proszę je rozwiązać, zanim będziemy mogli ocenić pull request."
